import { NewsArticle, CategoryType } from './types';

export const CATEGORIES = [
  { id: CategoryType.National, bn: 'জাতীয়', en: 'National' },
  { id: CategoryType.International, bn: 'আন্তর্জাতিক', en: 'International' },
  { id: CategoryType.Politics, bn: 'রাজনীতি', en: 'Politics' },
  { id: CategoryType.Economy, bn: 'অর্থনীতি', en: 'Economy' },
  { id: CategoryType.Sports, bn: 'খেলা', en: 'Sports' },
  { id: CategoryType.Entertainment, bn: 'বিনোদন', en: 'Entertainment' },
  { id: CategoryType.Technology, bn: 'প্রযুক্তি', en: 'Technology' },
  { id: CategoryType.Campus, bn: 'ক্যাম্পাস', en: 'Campus' },
  { id: CategoryType.Education, bn: 'শিক্ষা', en: 'Education' },
  { id: CategoryType.Job, bn: 'চাকরি', en: 'Job' },
  { id: CategoryType.Lifestyle, bn: 'লাইফস্টাইল', en: 'Lifestyle' },
  { id: CategoryType.Health, bn: 'স্বাস্থ্য', en: 'Health' },
  { id: CategoryType.Crime, bn: 'অপরাধ', en: 'Crime' },
  { id: CategoryType.Agriculture, bn: 'কৃষি', en: 'Agriculture' },
  { id: CategoryType.Travel, bn: 'ভ্রমণ', en: 'Travel' },
  { id: CategoryType.Probash, bn: 'প্রবাস', en: 'Expatriates' },
  { id: CategoryType.Science, bn: 'বিজ্ঞান', en: 'Science' },
  { id: CategoryType.Environment, bn: 'পরিবেশ', en: 'Environment' },
  { id: CategoryType.Law, bn: 'আইন ও বিচার', en: 'Law & Justice' },
  { id: CategoryType.Religion, bn: 'ধর্ম', en: 'Religion' },
  { id: CategoryType.Literature, bn: 'সাহিত্য', en: 'Literature' },
  { id: CategoryType.Corporate, bn: 'করপোরেট', en: 'Corporate' },
  { id: CategoryType.Multimedia, bn: 'মাল্টিমিডিয়া', en: 'Multimedia' },
  { id: CategoryType.Auto, bn: 'মোটরযান', en: 'Automobile' },
  { id: CategoryType.Feature, bn: 'ফিচার', en: 'Feature' },
  { id: CategoryType.Opinion, bn: 'মতামত', en: 'Opinion' },
  { id: CategoryType.Special, bn: 'বিশেষ প্রতিবেদন', en: 'Special Reports' },
];

export const MOCK_ARTICLES: NewsArticle[] = [
  {
    id: '1',
    title: { bn: 'সারাদেশে শীতের দাপট, তাপমাত্রা আরও কমার আভাস', en: 'Winter wave across the country, temperature may drop further' },
    excerpt: { bn: 'দেশের উত্তরাঞ্চলে হিমেল হাওয়ায় বিপর্যস্ত জনজীবন। আবহাওয়া অফিস জানিয়েছে...', en: 'Public life disrupted by chilly winds in northern regions. The weather office says...' },
    content: { bn: 'বিস্তারিত সংবাদ এখানে...', en: 'Full news details here...' },
    category: CategoryType.National,
    authorId: 'admin-1',
    authorName: 'রিপোর্ট প্রতিবেদক',
    status: 'published',
    publishedAt: new Date().toISOString(),
    image: 'https://picsum.photos/seed/winter/800/450',
    tags: ['শীত', 'আবহাওয়া'],
    views: 1250,
    isBreaking: true,
    isFeatured: true
  },
  {
    id: '2',
    title: { bn: 'ক্যাম্পাসে নতুন নীতিমালা নিয়ে শিক্ষার্থীদের বিক্ষোভ', en: 'Students protest over new campus policies' },
    excerpt: { bn: 'বিশ্ববিদ্যালয় প্রশাসনের নতুন সিদ্ধান্তের প্রতিবাদে সাধারণ শিক্ষার্থীরা মানববন্ধন করেছে।', en: 'General students formed a human chain protesting the new decision of the university administration.' },
    content: { bn: 'বিস্তারিত সংবাদ এখানে...', en: 'Full news details here...' },
    category: CategoryType.Campus,
    authorId: 'admin-1',
    authorName: 'ক্যাম্পাস প্রতিনিধি',
    status: 'published',
    publishedAt: new Date().toISOString(),
    image: 'https://picsum.photos/seed/campus/800/450',
    tags: ['শিক্ষা', 'ক্যাম্পাস'],
    views: 840,
    isBreaking: true
  }
];